services:
  db:
    image: mysql:latest
    container_name: apo_db
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql_data:/var/lib/mysql

  app:
    build: .  
    container_name: apo_app 
    volumes:
      - "./:/var/www/html"  
      - "./000-default.conf:/etc/apache2/sites-available/000-default.conf"  
    ports:
      - 8081:80  
      - 443:443  
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public  
    depends_on:
      - db  
    restart: always  
